# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['../src/cli.py'],
    pathex=['../src'],
    binaries=[],
    datas=[
        ("../src/infrastructure/catalog/catalog.json", "infrastructure/catalog"),
        ("../alembic", "alembic"),
        ("../alembic.ini", "."),
    ],
    hiddenimports=[
        "aiosqlite",
        "alembic",
        "alembic.runtime.migration",
        "alembic.script",
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'domain',
        'application',
        'application.use_cases.uninstall_mcp',
        'infrastructure.mcp.wrapper_runner',
        'infrastructure.mcp.wrapper_command',
        'keyring',
        'presentation',
        'shared',
        'mcp',
        'mcp_proxy',
        'mcp_proxy.__main__',
        'mcp_proxy.mcp_server',
        'mcp_proxy.proxy_server',
        'anyio._backends.asyncio',
        'keyring.backends.macOS',
        'httpx_auth',
        'uvicorn',
        'starlette',
        'anyio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mcpharbour-api',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
