# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['../src/cli.py'],
    pathex=['../src'],
    binaries=[],
    datas=[
        ("../src/infrastructure/catalog/catalog.json", "infrastructure/catalog"),
        ("../alembic", "alembic"),
        ("../alembic.ini", "."),
    ],
    hiddenimports=[
        "aiosqlite",
        "alembic",
        "alembic.runtime.migration",
        "alembic.script",
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'domain',
        'application',
        'application.use_cases.uninstall_mcp',
        'application.use_cases.agents',
        'application.use_cases.policies',
        'infrastructure.mcp.gateway',
        'infrastructure.mcp.unified_gateway',
        'infrastructure.mcp.gpars',
        'infrastructure.mcp.wrapper_runner',
        'infrastructure.mcp.wrapper_command',
        'infrastructure.policy.policy_service',
        'infrastructure.auth.token_service',
        'presentation.api.middleware.auth',
        'keyring',
        'presentation',
        'shared',
        'mcp',
        'mcp.client.stdio',
        'mcp.client.session',
        'mcp.client.streamable_http',
        'mcp.server.streamable_http',
        'mcp.server.streamable_http_manager',
        'mcp.server.session',
        'mcp.server.lowlevel',
        'mcp_proxy',
        'mcp_proxy.mcp_server',
        'mcp_proxy.proxy_server',
        'mcp_proxy.httpx_client',
        'mcp_proxy.streamablehttp_client',
        'anyio._backends._asyncio',
        'anyio._core._eventloop',
        'anyio._core._subprocesses',
        'anyio._core._streams',
        'anyio._core._sockets',
        'anyio._core._synchronization',
        'anyio._core._tasks',
        'anyio._core._fileio',
        'anyio.abc',
        'anyio.streams',
        'anyio.from_thread',
        'keyring.backends.macOS',
        'httpx_auth',
        'uvicorn',
        'starlette',
        'anyio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mcpharbour-api',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
